cattle-eks:
   rancher_cluster_name: "tk8-tpr2-eks"
   rancher_api_url: "https://gui.rancher.svc/v3"
   region: "eu-central-1"
   existing_vpc: false
   vpc_id:
   subnets:
      subnet_id1:
      subnet_id2:
      subnet_id3:
   security_group_name: 
   disk_size: "20"
   ami_id: "ami-058487fd109552697"
   kubernetes_version: "1.14"
   maximum_nodes: 3
   minimum_nodes: 1
   session_token:  
   instance_type: "t2.medium"
   associate_worker_node_public_ip: true 
   service_role:
